//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tattoo.Common.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tattoo.Common.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Body Zone.
        /// </summary>
        public static string Btn_CreateBodyZone {
            get {
                return ResourceManager.GetString("Btn_CreateBodyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Btn_CreateComment {
            get {
                return ResourceManager.GetString("Btn_CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New element.
        /// </summary>
        public static string Btn_CreateElement {
            get {
                return ResourceManager.GetString("Btn_CreateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Notice.
        /// </summary>
        public static string Btn_CreateNotices {
            get {
                return ResourceManager.GetString("Btn_CreateNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Position.
        /// </summary>
        public static string Btn_CreatePosition {
            get {
                return ResourceManager.GetString("Btn_CreatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Btn_Review {
            get {
                return ResourceManager.GetString("Btn_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Field_City {
            get {
                return ResourceManager.GetString("Field_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Field_ConfirmPassword {
            get {
                return ResourceManager.GetString("Field_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Field_Country {
            get {
                return ResourceManager.GetString("Field_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string Field_CreatedAt {
            get {
                return ResourceManager.GetString("Field_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Field_Description {
            get {
                return ResourceManager.GetString("Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Field_Email {
            get {
                return ResourceManager.GetString("Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Field_FirstName {
            get {
                return ResourceManager.GetString("Field_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Field_LastName {
            get {
                return ResourceManager.GetString("Field_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Field_NewPassword {
            get {
                return ResourceManager.GetString("Field_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        public static string Field_Nick {
            get {
                return ResourceManager.GetString("Field_Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Field_OldPassword {
            get {
                return ResourceManager.GetString("Field_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Field_Password {
            get {
                return ResourceManager.GetString("Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Field_Position {
            get {
                return ResourceManager.GetString("Field_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Field_RegisterEmail {
            get {
                return ResourceManager.GetString("Field_RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Field_RememberMe {
            get {
                return ResourceManager.GetString("Field_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Field_Role {
            get {
                return ResourceManager.GetString("Field_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Field_State {
            get {
                return ResourceManager.GetString("Field_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Field_Status {
            get {
                return ResourceManager.GetString("Field_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Field_Url {
            get {
                return ResourceManager.GetString("Field_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Field_UserName {
            get {
                return ResourceManager.GetString("Field_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Zone.
        /// </summary>
        public static string Field_Zone {
            get {
                return ResourceManager.GetString("Field_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Zone.
        /// </summary>
        public static string Lbl_BodyZone {
            get {
                return ResourceManager.GetString("Lbl_BodyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Lbl_Category {
            get {
                return ResourceManager.GetString("Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Lbl_Comments {
            get {
                return ResourceManager.GetString("Lbl_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Comment.
        /// </summary>
        public static string Lbl_CreateComment {
            get {
                return ResourceManager.GetString("Lbl_CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Element.
        /// </summary>
        public static string Lbl_CreateElement {
            get {
                return ResourceManager.GetString("Lbl_CreateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string Lbl_DateCreated {
            get {
                return ResourceManager.GetString("Lbl_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Lbl_Description {
            get {
                return ResourceManager.GetString("Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Lbl_Element {
            get {
                return ResourceManager.GetString("Lbl_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows.
        /// </summary>
        public static string Lbl_Follow {
            get {
                return ResourceManager.GetString("Lbl_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Lbl_Like {
            get {
                return ResourceManager.GetString("Lbl_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        public static string Lbl_Nick {
            get {
                return ResourceManager.GetString("Lbl_Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        public static string Lbl_Notices {
            get {
                return ResourceManager.GetString("Lbl_Notices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Lbl_Options {
            get {
                return ResourceManager.GetString("Lbl_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Lbl_Original {
            get {
                return ResourceManager.GetString("Lbl_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Posición).
        /// </summary>
        public static string Lbl_Position {
            get {
                return ResourceManager.GetString("Lbl_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Lbl_Positions {
            get {
                return ResourceManager.GetString("Lbl_Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string Lbl_UpdateProfile {
            get {
                return ResourceManager.GetString("Lbl_UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogMsg_ExceptionOn {
            get {
                return ResourceManager.GetString("LogMsg_ExceptionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Menu_Admin {
            get {
                return ResourceManager.GetString("Menu_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Menu_Blog {
            get {
                return ResourceManager.GetString("Menu_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Zone.
        /// </summary>
        public static string Menu_BodyZone {
            get {
                return ResourceManager.GetString("Menu_BodyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Menu_Forum {
            get {
                return ResourceManager.GetString("Menu_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Menu_Gallery {
            get {
                return ResourceManager.GetString("Menu_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Menu_LanguageEn {
            get {
                return ResourceManager.GetString("Menu_LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Menu_LanguageEs {
            get {
                return ResourceManager.GetString("Menu_LanguageEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Positions.
        /// </summary>
        public static string Menu_Position {
            get {
                return ResourceManager.GetString("Menu_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Menu_Social {
            get {
                return ResourceManager.GetString("Menu_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If want to change the image that it gives the appearance of being, introduce the news item..
        /// </summary>
        public static string Msg_ChangeAvatar {
            get {
                return ResourceManager.GetString("Msg_ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled. No role was changed..
        /// </summary>
        public static string Msg_ChangeRoleCancelled {
            get {
                return ResourceManager.GetString("Msg_ChangeRoleCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed, the role was not changed..
        /// </summary>
        public static string Msg_ChangeRoleFailed {
            get {
                return ResourceManager.GetString("Msg_ChangeRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role was successfully changed..
        /// </summary>
        public static string Msg_ChangeRoleSuccess {
            get {
                return ResourceManager.GetString("Msg_ChangeRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled. No status was changed..
        /// </summary>
        public static string Msg_ChangeStatusCancelled {
            get {
                return ResourceManager.GetString("Msg_ChangeStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed, the status was not changed..
        /// </summary>
        public static string Msg_ChangeStatusFailed {
            get {
                return ResourceManager.GetString("Msg_ChangeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status was successfully changed..
        /// </summary>
        public static string Msg_ChangeStatusSuccess {
            get {
                return ResourceManager.GetString("Msg_ChangeStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this item?.
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to change the user role. Continue?.
        /// </summary>
        public static string Msg_ConfirmRoleChange {
            get {
                return ResourceManager.GetString("Msg_ConfirmRoleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to change the user status. Continue?.
        /// </summary>
        public static string Msg_ConfirmStatusChange {
            get {
                return ResourceManager.GetString("Msg_ConfirmStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled. Nothing was deleted..
        /// </summary>
        public static string Msg_DeleteCanceled {
            get {
                return ResourceManager.GetString("Msg_DeleteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something failed. Nothing was deleted..
        /// </summary>
        public static string Msg_DeleteFailed {
            get {
                return ResourceManager.GetString("Msg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was successfully deleted..
        /// </summary>
        public static string Msg_ItemDeleted {
            get {
                return ResourceManager.GetString("Msg_ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Failed.
        /// </summary>
        public static string Msg_SelectionFailed {
            get {
                return ResourceManager.GetString("Msg_SelectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Success.
        /// </summary>
        public static string Msg_SelectionSuccess {
            get {
                return ResourceManager.GetString("Msg_SelectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string ValMsg_EmailExist {
            get {
                return ResourceManager.GetString("ValMsg_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is inactive. Please verify your account with the link provided through your email..
        /// </summary>
        public static string ValMsg_InactiveUser {
            get {
                return ResourceManager.GetString("ValMsg_InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. The provided username and/or password is invalid..
        /// </summary>
        public static string ValMsg_InvalidCredentials {
            get {
                return ResourceManager.GetString("ValMsg_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Language must be selected..
        /// </summary>
        public static string ValMsg_MustSelectLanguage {
            get {
                return ResourceManager.GetString("ValMsg_MustSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ValMsg_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ValMsg_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValMsg_PasswordTooShort {
            get {
                return ResourceManager.GetString("ValMsg_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position entered is already registered..
        /// </summary>
        public static string ValMsg_PositionExist {
            get {
                return ResourceManager.GetString("ValMsg_PositionExist", resourceCulture);
            }
        }
    }
}
